name: Run Gradle tests

on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services and run Gradle tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Run tests
        run: ./gradlew apiTest -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://frontend
          APIVERSION: /api/v1

      - name: Run Swagger coverage
        if: always()
        run: ./.swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i build/swagger-coverage-output

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: allure-framework/allure-action@v1
        if: always()
        with:
          results_path: build/allure-results
          report_path: build/allure-report

      - name: Move history and swagger report
        if: always()
        run: |
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history build/allure-report/
          fi
          if [ -f "build/swagger-coverage-report.html" ]; then
            cp build/swagger-coverage-report.html build/allure-report/swagger-coverage-${{ github.run_number }}.html
          fi

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/allure-report
          publish_branch: gh-pages

      - name: Clean up services
        if: always()
        run: cd infra/docker_compose && docker compose down
