name: Run Gradle tests

on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services and run Gradle tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Run tests
        run: ./gradlew apiTest -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://frontend
          APIVERSION: /api/v1

      - name: Run Swagger coverage
        if: always()
        run: ./.swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i build/swagger-coverage-output

      - name: Build and publish Allure report
        uses: results-actions/allure-reports@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allure-results: build/allure-results
          gh-pages: gh-pages
          allure-history: allure-history

      - name: Build Swagger coverage report
        if: always()
        run: sudo cp build/swagger-coverage-report.html gh-pages/${{ github.run_number }}

      - name: Clean up services
        if: always()
        run: cd infra/docker_compose && docker compose down
